# lightning.pytorch==2.3.3
seed_everything: 0
trainer:
  accelerator: gpu
  strategy: ddp
  devices: 1
  num_nodes: 1
  precision: 32-true
  logger: null
  callbacks: null
  fast_dev_run: false
  max_epochs: null
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: 1000
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: null
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 2
  gradient_clip_val: 0.5
  gradient_clip_algorithm: norm
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins:
    - class_path: lightning.fabric.plugins.environments.SLURMEnvironment
      init_args:
        auto_requeue: true
        requeue_signal: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
model:
  vf_model:
    class_path: networks.AttnUNetF
    init_args:
      n_updown_levels: 5
      in_channels: 3
      hidden_channels: [128, 256, 512, 768, 1024, 2048]
      out_channels: 3
      emb_channels: 128
      rotary_dims: 16
      band_embedding_dim: 16
      n_attn_heads: 8
      attention_levels:
        - 3
        - 4
      use_attn_input_norm: true
      num_res_blocks: 2
  inv_transforms:
    - class_path: audio_transforms.transforms.PowerScaleSpectrogram
      init_args:
        power: 4
        channels:
          - 0
        eps: 1.0e-09
    - class_path: audio_transforms.transforms.SpectrogramAddDCTerm
    - class_path: audio_transforms.transforms.SVDFixMagInstPhase
    - class_path: audio_transforms.transforms.MagInstPhaseToComplex
    - class_path: audio_transforms.transforms.InverseComplexSpectrogram
      init_args:
        n_fft: 2048
        win_length: 2048
        hop_length: 512
        eps: 1.0e-09
  sampling_rate: 44100
  n_timestep_channels: 128
  use_ot_ode: false
  beta_max: 1.0
  pretrained_checkpoints:
    - PATH/TO/FIRST/SPLIT.ckpt
    - PATH/TO/SECOND/SPLIT.ckpt
  t_cutoffs: [ 0.5 ]
data:
  mix_dataset_config:
    EVAL_DATASET_NAME:
      root_folder: PATH/TO/MANIFEST/FOLDER
      filename: 'EVAL_DATASET_NAME_manifest.csv'
    EVAL_DATASET_NAME_TWO:
      root_folder: PATH/TO/MANIFEST/FOLDER
      filename: 'EVAL_DATASET_NAME_TWO_manifest.csv'

  segment_length: 130560
  sampling_rate: 44100
  num_workers: 23
  batch_size: 4
  
  transforms_aug: []
  transforms_aug_val: []
  eval_transforms_aug: []

  transforms_gt:
    - class_path: audio_transforms.transforms.ComplexSpectrogram
      init_args:
        n_fft: 2048
        win_length: 2048
        hop_length: 512
        eps: 1.0e-09
    - class_path: audio_transforms.transforms.ComplexToMagInstPhase
    - class_path: audio_transforms.transforms.SpectrogramDropDCTerm
    - class_path: audio_transforms.transforms.PowerScaleSpectrogram
      init_args:
        power: 0.25
        channels:
          - 0
        eps: 1.0e-09
  train_max_samples: null
  val_max_samples: 256
  predict_filelist: []
