data:
  predict_filelist:
    - filepath: "dummy1.wav"
      output_subdir: "dummy1"
    - filepath: "dummy2.wav"
      output_subdir: "dummy2"
      
  transforms_gt:
    - class_path: audio_transforms.transforms.ComplexSpectrogram
      init_args:
        n_fft: 2048
        win_length: 2048
        hop_length: 512
    - class_path: audio_transforms.transforms.ComplexToMagInstPhase
    - class_path: audio_transforms.transforms.SpectrogramDropDCTerm
    - class_path: audio_transforms.transforms.PowerScaleSpectrogram
      init_args:
        power: 0.25
        channels:
          - 0
          
  transforms_aug:
    - class_path: corruption.corruptions.MultinomialInpaintMaskTransform
      init_args:
        p_upsample_mask: 1.0
        p_extension_mask: 0.0
        p_inpaint_mask: 0.0
        fill_noise_level: 0.5
        sampling_rate: 44100
        upsample_mask_kwargs:
          min_cutoff_freq: 2000
          max_cutoff_freq: 2000
        inpainting_mask_kwargs:
          min_inpainting_frac: 0.1013
          max_inpainting_frac: 0.1013
          is_random: false
