# lightning.pytorch==2.0.8
seed_everything: true
trainer:
  accelerator: gpu
  strategy: ddp
  devices: 8
  num_nodes: 4
  precision: bf16-mixed
  logger: null
  callbacks: null
  fast_dev_run: false
  max_epochs: null
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: 1000
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: null
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: 0.5
  gradient_clip_algorithm: norm
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins:
    - class_path: lightning.fabric.plugins.environments.SLURMEnvironment
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null


model:
  vf_model:
    class_path: networks.AttnUNetF
    init_args:
      n_updown_levels: 5
      in_channels: 3
      hidden_channels: [128, 256, 512, 768, 1024, 2048]
      out_channels: 3
      emb_channels: 128
      band_embedding_dim: 16
      n_attn_heads: 8
      attention_levels:
        - 3
        - 4
      use_attn_input_norm: true
      num_res_blocks: 2
  inv_transforms:
    - class_path: audio_transforms.transforms.PowerScaleSpectrogram
      init_args:
        power: 4
        channels:
          - 0
    - class_path: audio_transforms.transforms.SpectrogramAddDCTerm
    - class_path: audio_transforms.transforms.MagInstPhaseToComplex
    - class_path: audio_transforms.transforms.InverseComplexSpectrogram
      init_args:
        n_fft: 2048
        win_length: 2048
        hop_length: 512
  sampling_rate: 44100
  n_timestep_channels: 128
  use_ot_ode: false
  beta_max: 1.0
  learning_rate: 0.00008

data:
  mix_dataset_config:
    TRAIN_DATASET_NAME:
      root_folder: PATH/TO/MANIFEST/FOLDER
      filename: 'TRAIN_DATASET_NAME_manifest.csv'
    TRAIN_DATASET_NAME_TWO:
      root_folder: PATH/TO/MANIFEST/FOLDER
      filename: 'TRAIN_DATASET_NAME_TWO_manifest.csv'
    

  segment_length: 130560
  sampling_rate: 44100
  num_workers: 23
  batch_size: 10
  val_max_samples: 256

  transforms_aug:
    - class_path: corruption.corruptions.MultinomialInpaintMaskTransform
      init_args:
        p_upsample_mask: 0.5
        p_extension_mask: 0.0
        p_inpaint_mask: 0.5
        fill_noise_level: 0.5
        sampling_rate: 44100
        upsample_mask_kwargs:
          min_cutoff_freq: 2000
          max_cutoff_freq: 16000
        inpainting_mask_kwargs:
          min_inpainting_frac: 0.03378
          max_inpainting_frac: 0.5404
          is_random: true
  
  eval_transforms_aug:
    - class_path: corruption.corruptions.MultinomialInpaintMaskTransform
      init_args:
        p_upsample_mask: 0.5
        p_extension_mask: 0.0
        p_inpaint_mask: 0.5
        fill_noise_level: 0.5
        sampling_rate: 44100
        upsample_mask_kwargs:
          min_cutoff_freq: 4000
          max_cutoff_freq: 4000
        inpainting_mask_kwargs:
          min_inpainting_frac: 0.1013
          max_inpainting_frac: 0.1013
          is_random: false

  transforms_gt:
    - class_path: audio_transforms.transforms.ComplexSpectrogram
      init_args:
        n_fft: 2048
        win_length: 2048
        hop_length: 512
    - class_path: audio_transforms.transforms.ComplexToMagInstPhase
    - class_path: audio_transforms.transforms.SpectrogramDropDCTerm
    - class_path: audio_transforms.transforms.PowerScaleSpectrogram
      init_args:
        power: 0.25
        channels:
          - 0

checkpoint_callback:
  dirpath: exp/pretrain
  every_n_train_steps: 1000
